name: Checkout

on: [push]

jobs:
  execute-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout step
        uses: actions/checkout@v4
      - name: setup node step
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: install dependencies step
        run: npm install
      - name: execute cypress step
        run: npx cypress run
      - name: generate screenshots step
        uses: actions/upload-artifact@v4
        if: failure()
        with: 
          name: screenshots
          path: cypress/screenshots
      - name: generate videos step
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: videos
          path: cypress/videos
